services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tareas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"    # <-- cambia 5432 por 5433 en el host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tareas_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: